algo: ac
envparameters:
  action_continuous: false
  action_space: 2
  n_player: 1
  obs_continuous: true
  obs_space: 4
  scenario: classic_CartPole-v0
hyperparameters:
  batch_size: 32
  buffer_capacity: 100
  c_lr: 0.005
  gamma: 0.99
  hidden_size: 100
  given_net: False
seedparameters:
  seed_nn: 1
  seed_np: 1
  seed_random: 1
trainingparameters:
  evaluate_rate: 50
  learn_freq: 10
  learn_terminal: true
  max_episodes: 10000
  render: false
  save_interval: 50
