a_lr: 0.0001
action_space: 3
algo: ddpg
alpha: 0.2
alpha_lr: 0.0001
batch_size: 64
buffer_capacity: 10000
c_lr: 0.0001
clip_param: 0.2
epsilon: 0.5
epsilon_end: 0.05
evaluate_rate: 50
gamma: 0.99
hidden_size: 100
learn_freq: 1
learn_terminal: false
max_episodes: 1000
max_grad_norm: 0.5
obs_space: 2
ppo_update_time: 10
reload_config: false
run_redo: null
scenario: classic_MountainCar-v0
seed_nn: 1
seed_np: 1
seed_random: 1
target_entropy_ratio: 0.9
target_replace: 100
tau: 0.02
train_frequency: 100
tune_entropy: false
update_freq: 1
