a_lr: 0.005
action_space: 2
algo: dqn
batch_size: 64
buffer_capacity: 256
c_lr: 0.005
clip_param: 0.2
epsilon: 0.5
epsilon_end: 0.05
evaluate_rate: 50
gamma: 0.99
hidden_size: 100
max_episodes: 1000
max_grad_norm: 0.5
obs_space: 4
ppo_update_time: 10
reload_config: false
run_redo: null
scenario: classic_CartPole-v0
seed_nn: 1
seed_np: 1
seed_random: 1
target_replace: 100
train_frequency: 100
