a_lr: 0.0001
action_space: 3
algo: ppo_cnn
batch_size: 32
buffer_capacity: 10000
c_lr: 0.0001
clip_param: 0.1
epsilon: 0.5
epsilon_end: 0.05
evaluate_rate: 50
gamma: 0.9
hidden_size: 100
is_matrix: true
learn_freq: 1
learn_terminal: true
max_episodes: 180
max_grad_norm: 0.5
obs_space: !!python/tuple
- 60
- 80
- 3
ppo_update_time: 12
reload_config: false
run_redo: null
scenario: MiniWorld-OneRoom-v0
seed_nn: 1
seed_np: 1
seed_random: 1
target_replace: 100
tau: 0.02
train_frequency: 100
update_freq: 10
