a_lr: 0.001
action_space: 3
algo: ppo
batch_size: 32
buffer_capacity: 1000
c_lr: 0.001
clip_param: 0.2
epsilon: 0.99
epsilon_end: 0.05
evaluate_rate: 50
gamma: 0.99
hidden_size: 100
learn_freq: 1
learn_terminal: true
max_episodes: 3000
max_grad_norm: 0.5
obs_space: 2
ppo_update_time: 10
reload_config: false
run_redo: null
scenario: classic_MountainCar-v0
seed_nn: 1
seed_np: 1
seed_random: 1
target_replace: 100
tau: 0.02
train_frequency: 100
update_freq: 10
