a_lr: 0.0001
action_space: 2
algo: sac
alpha: 0.2
alpha_lr: 0.0001
batch_size: 32
buffer_capacity: 1000
c_lr: 0.0001
clip_param: 0.2
epsilon: 0.02
epsilon_end: 0.05
evaluate_rate: 50
gamma: 0.99
hidden_size: 128
learn_freq: 1
learn_terminal: false
max_episodes: 1000
max_grad_norm: 0.5
obs_space: 4
reload_config: false
run_redo: null
scenario: classic_CartPole-v0
seed_nn: 1
seed_np: 1
seed_random: 1
target_entropy_ratio: 0.95
target_replace: 30
tau: 0.005
tune_entropy: true
update_freq: 10
