algo: sac
envparameters:
  action_continuous: false
  action_space: 2
  n_player: 1
  obs_continuous: true
  obs_space: 4
  scenario: classic_CartPole-v0
hyperparameters:
  batch_size: 32
  buffer_capacity: 1000
  c_lr: 0.0001
  a_lr: 0.0001
  alpha_lr: 0.0001
  alpha: 0.2
  epsilon: 0.02
  epsilon_end: 0.05
  gamma: 0.99
  hidden_size: 128
  num_hid_layer: 1
  target_replace: 30
  network: critic
  policy_type: discrete
  clip_param: 0.2
  target_entropy_ratio: 0.7
  tau: 0.005
  tune_entropy: false
seedparameters:
  seed_nn: 1
  seed_np: 1
  seed_random: 1
trainingparameters:
  evaluate_rate: 50
  learn_freq: 1
  learn_terminal: false
  max_episodes: 1000
  render: false
  save_interval: 50
