algo: td3
envparameters:
  action_continuous: true
  action_space: 1
  n_player: 1
  obs_continuous: true
  obs_space: 3
  scenario: classic_Pendulum-v0
hyperparameters:
  a_lr: 3e-4
  batch_size: 100
  buffer_capacity: 10240
  c_lr: 3e-4
  epsilon: 0.3
  epsilon_end: 0.05
  exploration_noise: 0.1
  gamma: 0.99
  given_net: false
  hidden_size: 100
  network: network_td3
  noise_clip: 0.5
  policy_delay: 2
  policy_noise: 0.2
  target_replace: 100
  tau: 0.005
  update_freq: 10
seedparameters:
  seed_nn: 1
  seed_np: 1
  seed_random: 1
trainingparameters:
  evaluate_rate: 50
  learn_freq: 10
  learn_terminal: true
  max_episodes: 2000
  render: false
  save_interval: 50
